### ISSUE TITLE
no backround 

### ISSUE THREAD

**Issue by Leonavich** [sang765/Anicord-Theme#2]
There is no custom backround for some reason
![изображение_2024-12-28_215216832](https://github.com/user-attachments/assets/689a668d-5098-4b51-b890-4c770b56fd85)

**Comment by sang765** [comment]
Sorry for that, u can try new `--app-bg` link: https://sang765.github.io/Anicord-Theme/assets/themeimage.png
in theme ditor. Aslo u can try redownload in [releases](https://github.com/sang765/Anicord-Theme/releases)
